# Generated by Django 3.2.8 on 2021-11-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
